/**
 * A Snowflake is a unique ID generated by the current time, able to be checked for ordering.
 */
export type Snowflake = string;

/**
 * A Base64 version of the users snowflake
 */
export type TokenID = Snowflake;

/**
 * A base64 encoded hexadecimal value of how long it has been since 1970
 */
export type TokenTimestamp = string;

/**
 * An absurdly large random number converted to hex and then hashed
 */
export type TokenSecret = string;
export type Token = `${TokenID}.${TokenTimestamp}.${TokenSecret}`

export type EmailAddress = `${string}@${string}.${string}`

/**
 * Creates a {@link TokenTimestamp} value from the time when called 
 * 
 * **Returns:** {@link TokenTimestamp}
 */
export function tokenCreationTime() {
    return Buffer.from(Date.now().toString(16)).toBase64();
}

export interface Message {
    author_id : Snowflake
    channel_id: Snowflake
    server_id?: Snowflake

    content: string
}

export interface BaseUser {
    username: string
    email: EmailAddress
}

export interface PartialUser {

}

export interface Credentials {
    user_id  : Snowflake
    token    : Token  // Must be salted and hashed
    password : string // Must be salted and hashed
}